export const allArgOptions = {
	author: { description: "", docsSection: "optional", type: "string" },
	base: { description: "", docsSection: "core", type: "string" },
	"create-repository": {
		description: "",
		docsSection: "core",
		type: "boolean",
	},
	description: { description: "", docsSection: "core", type: "string" },
	email: { description: "", docsSection: "optional", type: "string" },
	"exclude-compliance": {
		description: "",
		docsSection: "opt-out",
		type: "boolean",
	},
	"exclude-contributors": {
		description: "",
		docsSection: "opt-out",
		type: "boolean",
	},
	"exclude-lint-json": {
		description: "",
		docsSection: "opt-out",
		type: "boolean",
	},
	"exclude-lint-knip": {
		description: "",
		docsSection: "opt-out",
		type: "boolean",
	},
	"exclude-lint-md": {
		description: "",
		docsSection: "opt-out",
		type: "boolean",
	},
	"exclude-lint-package-json": {
		description: "",
		docsSection: "opt-out",
		type: "boolean",
	},
	"exclude-lint-packages": {
		description: "",
		docsSection: "opt-out",
		type: "boolean",
	},
	"exclude-lint-perfectionist": {
		description: "",
		docsSection: "opt-out",
		type: "boolean",
	},
	"exclude-lint-spelling": {
		description: "",
		docsSection: "opt-out",
		type: "boolean",
	},
	"exclude-lint-yml": {
		description: "",
		docsSection: "opt-out",
		type: "boolean",
	},
	"exclude-releases": {
		description: "",
		docsSection: "opt-out",
		type: "boolean",
	},
	"exclude-renovate": {
		description: "",
		docsSection: "opt-out",
		type: "boolean",
	},
	"exclude-tests": { description: "", docsSection: "opt-out", type: "boolean" },
	funding: { description: "", docsSection: "optional", type: "string" },
	mode: { description: "", docsSection: "core", type: "string" },
	owner: { description: "", docsSection: "core", type: "string" },
	repository: { description: "", docsSection: "core", type: "string" },
	"skip-github-api": {
		description: "",
		docsSection: "opt-out",
		type: "boolean",
	},
	"skip-install": { description: "", docsSection: "opt-out", type: "boolean" },
	"skip-removal": { description: "", docsSection: "opt-out", type: "boolean" },
	"skip-restore": { description: "", docsSection: "opt-out", type: "boolean" },
	"skip-uninstall": {
		description: "",
		docsSection: "opt-out",
		type: "boolean",
	},
	title: { description: "", docsSection: "core", type: "string" },
} as const;
