declare namespace package_json_d_exports {
  export { _author5 as author, _bin9 as bin, _exports as default, _dependencies13 as dependencies, _description2 as description, _devDependencies14 as devDependencies, _engines16 as engines, _exports8 as exports, _files10 as files, _license4 as license, _lint_staged12 as "lint-staged", _name0 as name, _packageManager15 as packageManager, _repository3 as repository, _scripts11 as scripts, _sideEffects6 as sideEffects, _type7 as type, _version1 as version };
}
declare const _exports: {
  name: string;
  version: string;
  description: string;
  repository: {
    type: string;
    url: string;
  };
  license: string;
  author: {
    name: string;
    email: string;
  };
  sideEffects: boolean;
  type: string;
  exports: {
    ".": string;
  };
  bin: string;
  files: string[];
  scripts: {
    build: string;
    format: string;
    lint: string;
    "lint:knip": string;
    "lint:spelling": string;
    prepare: string;
    test: string;
  };
  "lint-staged": {
    "*": string;
  };
  dependencies: {
    "@typescript-eslint/typescript-estree": string;
    bingo: string;
    "bingo-fs": string;
    "bingo-stratum": string;
    "cached-factory": string;
    "cspell-populate-words": string;
    execa: string;
    "git-url-parse": string;
    "github-default-labels": string;
    "html-to-text": string;
    "image-size": string;
    "input-from-file": string;
    "input-from-file-json": string;
    "input-from-script": string;
    "js-yaml": string;
    json5: string;
    "lazy-value": string;
    lodash: string;
    marked: string;
    "npm-user": string;
    "object-strings-deep": string;
    "parse-author": string;
    "parse-package-name": string;
    "remove-dependencies": string;
    "remove-undefined-objects": string;
    semver: string;
    "set-github-repository-labels": string;
    "sort-keys": string;
    "sort-package-json": string;
    "title-case": string;
    "trash-cli": string;
    zod: string;
    "zod-package-json": string;
    "zod-tsconfig": string;
  };
  devDependencies: {
    "@eslint-community/eslint-plugin-eslint-comments": string;
    "@eslint/js": string;
    "@eslint/markdown": string;
    "@prettier/sync": string;
    "@release-it/conventional-changelog": string;
    "@types/html-to-text": string;
    "@types/lodash": string;
    "@types/node": string;
    "@types/parse-author": string;
    "@types/semver": string;
    "@vitest/coverage-v8": string;
    "@vitest/eslint-plugin": string;
    "all-contributors-cli": string;
    "bingo-requests": string;
    "bingo-stratum-testers": string;
    "bingo-testers": string;
    "console-fail-test": string;
    cspell: string;
    eslint: string;
    "eslint-plugin-jsdoc": string;
    "eslint-plugin-jsonc": string;
    "eslint-plugin-markdown-links": string;
    "eslint-plugin-n": string;
    "eslint-plugin-package-json": string;
    "eslint-plugin-perfectionist": string;
    "eslint-plugin-regexp": string;
    "eslint-plugin-yml": string;
    husky: string;
    knip: string;
    "lint-staged": string;
    prettier: string;
    "prettier-plugin-curly": string;
    "prettier-plugin-packagejson": string;
    "prettier-plugin-padding-lines": string;
    "prettier-plugin-sentences-per-line": string;
    "prettier-plugin-sh": string;
    "release-it": string;
    tsdown: string;
    typescript: string;
    "typescript-eslint": string;
    vitest: string;
  };
  packageManager: string;
  engines: {
    node: string;
  };
};
declare let _name0: typeof _exports["name"];
declare let _version1: typeof _exports["version"];
declare let _description2: typeof _exports["description"];
declare let _repository3: typeof _exports["repository"];
declare let _license4: typeof _exports["license"];
declare let _author5: typeof _exports["author"];
declare let _sideEffects6: typeof _exports["sideEffects"];
declare let _type7: typeof _exports["type"];
declare let _exports8: typeof _exports["exports"];
declare let _bin9: typeof _exports["bin"];
declare let _files10: typeof _exports["files"];
declare let _scripts11: typeof _exports["scripts"];
declare let _lint_staged12: typeof _exports["lint-staged"];
declare let _dependencies13: typeof _exports["dependencies"];
declare let _devDependencies14: typeof _exports["devDependencies"];
declare let _packageManager15: typeof _exports["packageManager"];
declare let _engines16: typeof _exports["engines"];
//#endregion
export { _author5 as author, _bin9 as bin, _exports as default, _dependencies13 as dependencies, _description2 as description, _devDependencies14 as devDependencies, _engines16 as engines, _exports8 as exports, _files10 as files, _license4 as license, _lint_staged12 as "lint-staged", _name0 as name, _packageManager15 as packageManager, package_json_d_exports, _repository3 as repository, _scripts11 as scripts, _sideEffects6 as sideEffects, _type7 as type, _version1 as version };