import { z } from "zod";

import { base } from "../base.ts";
import { formatIgnoreFile } from "./files/formatIgnoreFile.ts";
import { intakeFile } from "./intake/intakeFile.ts";

// Entries previously generated by create-typescript-app that are now outdated
const legacyIgnores = new Set([
	"/coverage*",
	"/lib",
	"coverage*/",
	"coverage/",
	"dist/",
	"lib/",
	"node_modules/",
]);

export const blockGitignore = base.createBlock({
	about: {
		name: "Gitignore",
	},
	addons: {
		ignores: z.array(z.string()).default([]),
	},
	intake({ files }) {
		const gitignore = intakeFile(files, [".gitignore"]);
		if (!gitignore) {
			return undefined;
		}

		return {
			ignores: gitignore[0]
				.split(/\r?\n/u)
				.map((line) => line.trim())
				.filter(
					(line) => line && !line.startsWith("#") && !legacyIgnores.has(line),
				),
		};
	},
	produce({ addons }) {
		const ignores = new Set(["/node_modules", ...addons.ignores]);

		// Negations must come after the patterns they negate
		const negations = [...ignores].filter((line) => line.startsWith("!"));
		const patterns = [...ignores].filter((line) => !line.startsWith("!"));

		return {
			files: {
				".gitignore": formatIgnoreFile([...patterns.sort(), ...negations]),
			},
		};
	},
});
