description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 9
    - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
      with:
        cache: pnpm
        node-version: "20"
    - run: pnpm install --frozen-lockfile
      shell: bash
  using: composite
