jobs:
  are_the_types_wrong:
    name: Are The Types Wrong?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: npx --yes @arethetypeswrong/cli --pack . --ignore-rules cjs-resolves-to-esm --profile esm-only
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: node ./lib/index.js --version
  dedupe_check:
    name: Dedupe Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm dedupe --check
  engines_check:
    name: Engines Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          cache: pnpm
          node-version: 22.23.2
      - run: pnpm install --prod --engine-strict --ignore-scripts
  format_check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm format --list-different
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: pnpm lint
  lint_knip:
    name: Lint Knip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm lint:knip
  lint_spelling:
    name: Lint Spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm lint:spelling
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm run test --coverage
      - env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: always()
        uses: codecov/codecov-action@v3
  type_check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/prepare
      - run: pnpm tsc

name: CI

on:
  pull_request: ~
  push:
    branches:
      - main
