jobs:
  contributors:
    permissions:
      actions: read
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: JoshuaKGoldberg/all-contributors-auto-action@c578423db9b2c14d3cee9c72f6c2aed31c128030 # v0.7.0

name: Contributors

on:
  push:
    branches:
      - main
