jobs:
  knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: pnpm lint:knip

name: Lint Knip

on:
  pull_request:

  push:
    branches:
      - main
