jobs:
  lint_knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: ./.github/actions/prepare
      - run: pnpm lint:knip

name: Lint Knip

on:
  pull_request: ~
  push:
    branches:
      - main
