jobs:
  octoguide:
    if: ${{ !endsWith(github.actor, '[bot]') }}
    permissions:
      discussions: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: JoshuaKGoldberg/octoguide@7fb7583381525bcdd9aabbfab291e21bae8de81e # 0.26.0
        with:
          config: strict
          github-token: ${{ secrets.GITHUB_TOKEN }}

name: OctoGuide

on:
  discussion:
    types:
      - created
      - edited
  discussion_comment:
    types:
      - created
      - deleted
      - edited
  issue_comment:
    types:
      - created
      - deleted
      - edited
  issues:
    types:
      - edited
      - opened
  pull_request_review_comment:
    types:
      - created
      - deleted
      - edited
  pull_request_target:
    types:
      - edited
      - opened
