jobs:
  post_release:
    name: Comment on relevant PRs and issues
    runs-on: ubuntu-latest
    steps:
      - uses: apexskier/github-release-commenter@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template: |
            :tada: This is included in version {release_link} :tada:

            The release is available on:

            * [npm package (@latest dist-tag)](https://www.npmjs.com/package/template-typescript-node-package/v/{release_tag})
            * [GitHub release](https://github.com/JoshuaKGoldberg/template-typescript-node-package/releases/tag/v{release_tag})

            Cheers! 📦🚀

name: Post Release

on:
  release:
    types: [published]
  workflow_dispatch: ~
