jobs:
  post_release:
    name: Comment on relevant PRs and issues
    runs-on: ubuntu-latest
    steps:
      - uses: apexskier/github-release-commenter@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template: |
            :tada: This is included in version {release_link} :tada:

name: Post-release

on:
  release:
    types: [published]
