concurrency:
  group: ${{ github.workflow }}

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        uses: JoshuaKGoldberg/release-it-action@d785123cf337c25cdfb43f24d6c98549123d7be2 # v0.5.7

name: Release

on:
  push:
    branches:
      - main
