name: Reviewdog

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - name: Prettier review
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          reporter: github-pr-review
          level: warning
          fail_on_error: false
          prettier_flags: "**/* --ignore-unknown"
